### ISSUE TITLE
Cannot import GPP.so to python

### ISSUE THREAD

**Issue by yf275** [Yelp/MOE#442]
Hi,

From python interactive shell, I got:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: No registered converter was able to produce a C++ rvalue of type std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > from this Python object of type str

from:

import moe.build.GPP as C_GP

Any suggestions would be appreciated!

**Comment by jialeiwang** [comment]
This is because your boost does not understand the compiled lib by your C++ compiler. Make sure that your boost version is new enough that supports the C++ compiler you are using. You can check the boost website and see which versions of C++ compiler your version of boost supports.

**Comment by suntzu86** [comment]
Sorry I've been gone for so long! See: #448 for details.

If you're still having issues after @jialeiwang's suggestions, can you provide some more info for us? OS, python version, etc. I've never seen this before. You can find software/library version requirements here: http://yelp.github.io/MOE/install.html
